import { StyleSheet } from 'react-native';

export const JSONRendererStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fafafa',
  },
  container: {
    flex: 1,
    padding: 8,
  },
  sectionContainer: {
    marginBottom: 8,
    position: 'relative',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
    paddingHorizontal: 2,
  },
  empty: {
    textAlign: 'center',
    color: '#999',
    marginTop: 20,
    fontStyle: 'italic',
    fontSize: 14,
  },
  addButtonContainer: {
    alignItems: 'flex-start',
  },
  addButton: {
    padding: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(74, 0, 224, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(74, 0, 224, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    padding: 4,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 71, 87, 0.1)',
  },
  editableContainer: {
    borderRadius: 8,
    padding: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  titleContainer: {
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(74, 0, 224, 0.8)',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1a1a1a',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  mainTitleContainer: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(74, 0, 224, 0.8)',
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#1a1a1a',
    textAlign: 'center',
    letterSpacing: -0.4,
    marginBottom: 8,
  },
  mainSummary: {
    fontSize: 16,
    lineHeight: 22,
    color: '#333',
    textAlign: 'center',
    fontStyle: 'italic',
    letterSpacing: -0.1,
  },
  mainTitleTouchable: {
    // No necesita estilos adicionales, hereda del contenedor padre
  },
  headingContainer: {
    marginBottom: 12,
    marginTop: 4,
  },
  heading: {
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  paragraphContainer: {
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 14,
    lineHeight: 20,
    color: '#333',
    letterSpacing: -0.1,
  },
  listContainer: {
    marginBottom: 12,
    marginLeft: 4,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  listIcon: {
    marginRight: 8,
    marginTop: 2,
  },
  listText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    color: '#333',
    letterSpacing: -0.1,
  },
  conceptContainer: {
    backgroundColor: 'rgba(74, 0, 224, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(74, 0, 224, 0.1)',
  },
  conceptTerm: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  conceptDefinition: {
    fontSize: 14,
    lineHeight: 20,
    color: '#333',
    marginBottom: 12,
    letterSpacing: -0.1,
  },
  examplesContainer: {
    backgroundColor: 'rgba(0, 128, 255, 0.03)',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 128, 255, 0.1)',
  },
  examplesTitle: {
    fontWeight: '600',
    color: '#0066cc',
    marginBottom: 8,
    fontSize: 13,
  },
  example: {
    fontSize: 12,
    color: '#333',
    marginBottom: 4,
    lineHeight: 16,
  },
  keyConceptsContainer: {
    backgroundColor: 'rgba(255, 193, 7, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 193, 7, 0.1)',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 12,
    letterSpacing: -0.2,
  },
  conceptsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  conceptPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(74, 0, 224, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  conceptPillText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '500',
  },
  summaryContainer: {
    backgroundColor: 'rgba(108, 117, 125, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(108, 117, 125, 0.1)',
  },
  summaryText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#333',
    letterSpacing: -0.1,
  },
  unknownContainer: {
    backgroundColor: 'rgba(153, 153, 153, 0.03)',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(153, 153, 153, 0.1)',
  },
  unknownText: {
    fontFamily: 'monospace',
    fontSize: 11,
    color: '#666',
    lineHeight: 14,
  },
  rawContainer: {
    backgroundColor: 'rgba(255, 193, 7, 0.05)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 193, 7, 0.2)',
  },
  rawTitle: {
    fontWeight: '600',
    color: '#856404',
    marginBottom: 8,
    fontSize: 14,
  },
  rawText: {
    fontFamily: 'monospace',
    fontSize: 11,
    color: '#333',
    lineHeight: 14,
  },
  selectedElement: {
    borderWidth: 2,
    borderColor: 'rgba(74, 0, 224, 0.3)',
    backgroundColor: 'rgba(74, 0, 224, 0.05)',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 16,
    width: '85%',
    maxWidth: 280,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#f8f9fa',
    marginBottom: 6,
  },
  modalOptionText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  modalCancel: {
    backgroundColor: '#f0f2f5',
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  modalCancelText: {
    color: '#666',
  },
  exampleContainer: {
    backgroundColor: 'rgba(0, 128, 255, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 128, 255, 0.1)',
  },
  exampleTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0066cc',
    marginBottom: 8,
  },
  exampleText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#333',
    letterSpacing: -0.1,
  },
  noteContainer: {
    backgroundColor: 'rgba(255, 193, 7, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 193, 7, 0.1)',
  },
  noteTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ad6800',
    marginBottom: 8,
  },
  noteText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#333',
    letterSpacing: -0.1,
  },
  quoteContainer: {
    backgroundColor: 'rgba(114, 46, 209, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(114, 46, 209, 0.1)',
  },
  quoteText: {
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
    color: '#391085',
    textAlign: 'center',
  },
  codeContainer: {
    backgroundColor: 'rgba(108, 117, 125, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(108, 117, 125, 0.1)',
  },
  codeText: {
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 16,
    color: '#333',
  },
  formulaContainer: {
    backgroundColor: 'rgba(74, 0, 224, 0.03)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(74, 0, 224, 0.1)',
  },
  formulaTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  formulaText: {
    fontFamily: 'monospace',
    fontSize: 14,
    color: '#333',
    marginBottom: 6,
  },
  formulaDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: '#666',
    marginTop: 8,
    fontStyle: 'italic',
  },
  addBottomContainer: {
    padding: 8,
    alignItems: 'flex-start',
    backgroundColor: '#fafafa',
  },
  addBottomButton: {
    padding: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(74, 0, 224, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(74, 0, 224, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
