services:
  - type: web
    name: studyscribe-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: BASE_URL
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
      - key: STRIPE_ENTERPRISE_PRICE_ID
        sync: false
      - key: MAX_FILE_SIZE
        value: 104857600
      - key: UPLOAD_DIR
        value: uploads/
      - key: EXPORTS_DIR
        value: exports/
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
      - key: FRONTEND_URL
        sync: false
