version: '3.8'

services:
  studyscribe-backend:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: studyscribe-backend
    environment:
      - BUILD_TIMESTAMP=${CURRENT_TIMESTAMP}
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./temp:/app/temp
    restart: unless-stopped
